---

# http://docs.adaptivecomputing.com/torque/6-1-0/adminGuide/help.htm
- hosts: localhost
  tasks:
    - include_vars: vault.yml
#    - name: configure hosts file
#      lineinfile:
#        dest: /etc/hosts
#        line: '192.168.50.5 client1'
#        create: yes
#      become: yes
#      become_user: root

# Some packages below were already installed from vagrant config file
# Wanted to make sure all delft3d dependencies managed here
    - name: install packages for building delft3d
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'subversion'
        - 'libtool'
        - 'libtool-ltdl'
        - 'libtool-ltdl-devel'
        - '"Development Tools"'


# Download source code
# Test if already downloaded
# Checkout subversion repository to specified folder.
    # create a directory if it doesn't exist
    - subversion:
        repo: https://svn.oss.deltares.nl/repos/delft3d/tags/6906
        username: "{{ svn_user }}"
        password: "{{ svn_pass }}"
        dest: /tmp/delft3d-repository


# compile steps
# cd /tmp/delft3d-repository/src
# run autogen.sh