---

# http://docs.adaptivecomputing.com/torque/6-1-0/adminGuide/help.htm
- hosts: vagrant
  tasks:
    - include_vars: vault.yml
#    - name: configure hosts file
#      lineinfile:
#        dest: /etc/hosts
#        line: '192.168.50.5 client1'
#        create: yes
#      become: yes
#      become_user: root

# Some packages below were already installed from vagrant config file
# Wanted to make sure all delft3d dependencies managed here
    - name: install packages for building delft3d
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'subversion'
        - 'libtool'
        - 'libtool-ltdl'
        - 'libtool-ltdl-devel'
        - '@Development Tools'
        - 'netcdf'
        - 'netcdf-devel'
        - 'netcdf-fortran-mpich'
        - 'netcdf-fortran-mpich-devel'
        - 'netcdf-mpich'
        - 'netcdf-mpich-devel'
        - 'expat-devel'
      become: yes


# Download source code
# Test if already downloaded
# Checkout subversion repository to specified folder.
    # create a directory if it doesn't exist
    - subversion:
        repo: https://svn.oss.deltares.nl/repos/delft3d/tags/6906
        username: "{{ svn_user }}"
        password: "{{ svn_pass }}"
        dest: /tmp/delft3d-repository

 # Copy README from source code to local machine vagrant directory
    - name: copy delft3d README to local machine
      copy:
        src: /tmp/delft3d-repository/src/README
        dest: /vagrant/ignored/README
        mode: 0755
        remote_src: true


# compile steps
# cd /tmp/delft3d-repository/src
# run autogen.sh
